parameters:
    nsh:
        session_lifetime: %nsh.session_lifetime%
        session_prefix: %nsh.session_prefix%
services:
    mrsuh.session_handler:
        class: Mrsuh\NginxSessionHandlerBundle\Session\RedisSessionHandler
        arguments: [@snc_redis.default, @security.token_storage, %nsh%]
